import Head from 'next/head'
import { TodoForm } from '../components/TodoForm'
import { TodoList } from '../components/TodoList'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { useCookies } from "react-cookie";
import { CookiesProvider } from "react-cookie";
import { useTodo } from "../hooks/useTodo";

export default function Home() {
  const [cookies, setCookie, removeCookie] = useCookies(['todos']);
  const {todos, taskName, taskDeadLine, addTodo, completeTodo, setTodos, setTaskName, setTaskDeadLine} = useTodo();

  useEffect(() => {
    setTodos(cookies.todos || [])
  }, [setTodos, cookies.todos])

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CookiesProvider>
        <TodoForm todos={todos} taskName={taskName} taskDeadLine={taskDeadLine} addTodo={addTodo} setTaskName={setTaskName} setTaskDeadLine={setTaskDeadLine}/>

        <h1>未完了</h1>
        <div>
          {todos?.map((todo, index) => { 
            if(!todo.complete){
              return (
                <TodoList {...todo} index={index} completeTodo={completeTodo} key={index}/>
              )
            }
          })}
        </div>

        <h1>完了済み</h1>
        {todos?.map((todo, index) => { 
          if(todo.complete){
            return (
              <TodoList {...todo} index={index} completeTodo={completeTodo} key={index}/>
            )
          }
        })}
      </CookiesProvider>
    </div>
  )
}
