import Head from 'next/head'
import { Footer } from '../components/Footter'
import { TodoForm } from '../components/TodoForm'
import { TodoList } from '../components/TodoList'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoForm />
        
      <TodoList title="洗濯" deadline="2022-12-30"/>
      
      <Footer />
    </div>
  )
}
