import Head from 'next/head'
import { TodoForm } from '../components/TodoForm'
import { TodoList } from '../components/TodoList'
import {useState ,useEffect} from 'react'
import styles from '../styles/Home.module.css'
import { useCookies } from "react-cookie";
import { CookiesProvider } from "react-cookie";

export default function Home() {
  const [cookies, setCookie, removeCookie] = useCookies(['todos']);
  const [todos, setTodos] = useState([]);
  const [taskName, setTaskName] = useState('');
  const [taskDeadLine, setTaskDeadLine] = useState('');

  useEffect(() => {
    setTodos(cookies.todos || [])
  }, [cookies.todos])

  const setTodoCookie = (input_todo)=>{
    console.log('setTodo')
    console.log(input_todo)
    setCookie('todos', input_todo);
  }

  const addTodo = () => {
    if(taskName == '' || taskDeadLine == ''){ 
      alert('項目を埋めてください。');
      return false; 
    }
    const input_todo = [...todos, {task_name: taskName, task_deadline: taskDeadLine, complete: false}];

    setTodos(input_todo);
    setTodoCookie(input_todo);
    setTaskName('');
    setTaskDeadLine('');
  }

  const completeTodo = (task_key) => {
    const change_todo = todos.map(
      (todo, index) => (index == task_key ? {task_name: todo.task_name, task_deadline: todo.task_deadline, complete: true} : todo)
    )
    setTodos(change_todo);
    setTodoCookie(change_todo);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CookiesProvider>
        <TodoForm todos={todos} taskName={taskName} taskDeadLine={taskDeadLine} addTodo={addTodo} setTaskName={setTaskName} setTaskDeadLine={setTaskDeadLine}/>
          
        <h1>未完了</h1>
        <div>
          {todos?.map((todo, index) => { 
            if(!todo.complete){
              return (
                <TodoList {...todo} index={index} completeTodo={completeTodo} key={index}/>
              )
            }
          })}
        </div>

        <h1>完了済み</h1>
        {todos?.map((todo, index) => { 
          if(todo.complete){
            return (
              <TodoList {...todo} index={index} completeTodo={completeTodo} key={index}/>
            )
          }
        })}
      </CookiesProvider>
    </div>
  )
}
